kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: cloudformation-operator
rules:
- apiGroups:
  - cloudformation.linki.space
  resources:
  - "*"
  verbs:
  - "*"

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: cloudformation-operator
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: cloudformation-operator
  apiGroup: rbac.authorization.k8s.io
